### ISSUE TITLE
app: publish colorful quran to playstore

### ISSUE THREAD

**Issue by lakuapik** [kodepandai/bak-ide#5]
@axmad386 aku punya akun google play publisher. what do you think?

**Comment by axmad386** [comment]
Boleh mas, tp rebuild ulang sih. Tp data json tajwid nanti ngambil dari repo colorful-quran bisa gak ya. Biar sinkron gitu kalau ada update rule tajwid

**Comment by lakuapik** [comment]
@axmad386 maksudnya data tajwid gimana mas?

**Comment by axmad386** [comment]
itu kan colorful-quran sekarang pwa. Kan gak bisa disubmit ke playstore. Harus bikin dari awal pake react native atau flutter. Tapi data jsonnya nanti ambil dari repo colorful-quran. Karena yang rumit sebenernya generate jsonnya, ada algoritmanya sendiri. Dan itu masih banyak yang kurang

**Comment by axmad386** [comment]
ini lho @lakuapik 
https://github.com/kodepandai/colorful-quran/tree/main/src/db/kemenag/surah

**Comment by lakuapik** [comment]
nek dibikin twa gitu? embed website gimana? nek native mesti ngoding lagi gak sih

**Comment by axmad386** [comment]
iya twa bisa sih, mau coba twa dulu? aku belum pernah tapi. Kayake mas @tamacroft lebih paham

**Comment by axmad386** [comment]
> nek dibikin twa gitu? embed website gimana? nek native mesti ngoding lagi gak sih

tapi nanti dia bakal pakai browser bawaan ya? karena colorful-quran ini rada problem juga di browser2 jadul. Hurufnya kepedot pas yang diwarnai. Di ios aja pernah tak coba ambyar. Yang aman di chrome e android 
Kedepan nek mau dibikin bagus ya tetep lebih baik native sih. Tp untku sementara twa gak masalah menurutku

**Comment by axmad386** [comment]
di hpne sampeyan aman mas @lakuapik yang ios? Coba ss halaman surat misal albaqoroh

**Comment by axmad386** [comment]
Ini tak close kah? Kn sudah terlaksana @lakuapik, hehe
